In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Data Pre-Processing
dataset = pd.read_csv('winequality-white.csv')
x = dataset.iloc[ : , [ 2 , 3 ]].values
y = dataset.iloc[ : , 4 ].values

df = pd.DataFrame(dataset)
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [2]:
# Splitting Dataset
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split( x , y , test_size = 0.50 , random_state = 0 )

In [3]:
# feature scaling

from sklearn.preprocessing import StandardScaler
st_x = StandardScaler()
x_train = st_x.fit_transform(x_train)
x_test = st_x.transform(x_test)

df = pd.DataFrame(x_test)
df

             0         1
0     0.153878 -0.987532
1    -0.616595  0.209842
2     3.492594 -0.947619
3     1.780432 -0.129414
4    -0.959027  1.157763
...        ...       ...
2444  0.239486 -1.047401
2445 -0.102946 -0.029633
2446 -0.188555 -0.967576
2447  0.153878  2.025859
2448 -1.130244 -0.787970

[2449 rows x 2 columns]

In [5]:
# Fitting Decision Tree Classifier to training set

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier( criterion = 'entropy' , random_state = 0 )
classifier.fit(x_train, y_train)

ValueError: Unknown label type: 'continuous'